# Generated by Django 5.0.3 on 2024-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('zone', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=500)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),

        #  migrations.RemoveField(
        # model_name='Fedback',
        # name='name',
    # ),
     ]
    
