# Generated by Django 5.0.3 on 2024-03-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_feedback_date_alter_feedback_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('agreereport', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=500)),
                ('option2', models.CharField(max_length=500)),
                ('option3', models.CharField(max_length=500)),
                ('option4', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('Reference', models.CharField(max_length=500)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
    ]
